/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FarmerIndexRouteImport } from './routes/farmer.index'
import { Route as FarmerProfileRouteImport } from './routes/farmer.profile'
import { Route as FarmerGrievanceRouteImport } from './routes/farmer.grievance'
import { Route as FarmerApplyRouteImport } from './routes/farmer.apply'
import { Route as FarmerApplicationsRouteImport } from './routes/farmer.applications'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSchemesRouteImport } from './routes/_app/schemes'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppGrievancesRouteImport } from './routes/_app/grievances'
import { Route as AppGisRouteImport } from './routes/_app/gis'
import { Route as AppFraudRouteImport } from './routes/_app/fraud'
import { Route as AppFieldVerificationRouteImport } from './routes/_app/field-verification'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppApplicationsRouteImport } from './routes/_app/applications'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerProfileRoute = FarmerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerGrievanceRoute = FarmerGrievanceRouteImport.update({
  id: '/grievance',
  path: '/grievance',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerApplyRoute = FarmerApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerApplicationsRoute = FarmerApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => FarmerRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSchemesRoute = AppSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppGrievancesRoute = AppGrievancesRouteImport.update({
  id: '/grievances',
  path: '/grievances',
  getParentRoute: () => AppRoute,
} as any)
const AppGisRoute = AppGisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => AppRoute,
} as any)
const AppFraudRoute = AppFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => AppRoute,
} as any)
const AppFieldVerificationRoute = AppFieldVerificationRouteImport.update({
  id: '/field-verification',
  path: '/field-verification',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/applications': typeof AppApplicationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/field-verification': typeof AppFieldVerificationRoute
  '/fraud': typeof AppFraudRoute
  '/gis': typeof AppGisRoute
  '/grievances': typeof AppGrievancesRoute
  '/reports': typeof AppReportsRoute
  '/schemes': typeof AppSchemesRoute
  '/settings': typeof AppSettingsRoute
  '/farmer/applications': typeof FarmerApplicationsRoute
  '/farmer/apply': typeof FarmerApplyRoute
  '/farmer/grievance': typeof FarmerGrievanceRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/': typeof FarmerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/applications': typeof AppApplicationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/field-verification': typeof AppFieldVerificationRoute
  '/fraud': typeof AppFraudRoute
  '/gis': typeof AppGisRoute
  '/grievances': typeof AppGrievancesRoute
  '/reports': typeof AppReportsRoute
  '/schemes': typeof AppSchemesRoute
  '/settings': typeof AppSettingsRoute
  '/farmer/applications': typeof FarmerApplicationsRoute
  '/farmer/apply': typeof FarmerApplyRoute
  '/farmer/grievance': typeof FarmerGrievanceRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer': typeof FarmerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/applications': typeof AppApplicationsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/field-verification': typeof AppFieldVerificationRoute
  '/_app/fraud': typeof AppFraudRoute
  '/_app/gis': typeof AppGisRoute
  '/_app/grievances': typeof AppGrievancesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/schemes': typeof AppSchemesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/farmer/applications': typeof FarmerApplicationsRoute
  '/farmer/apply': typeof FarmerApplyRoute
  '/farmer/grievance': typeof FarmerGrievanceRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/': typeof FarmerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/farmer'
    | '/login'
    | '/analytics'
    | '/applications'
    | '/dashboard'
    | '/field-verification'
    | '/fraud'
    | '/gis'
    | '/grievances'
    | '/reports'
    | '/schemes'
    | '/settings'
    | '/farmer/applications'
    | '/farmer/apply'
    | '/farmer/grievance'
    | '/farmer/profile'
    | '/farmer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/applications'
    | '/dashboard'
    | '/field-verification'
    | '/fraud'
    | '/gis'
    | '/grievances'
    | '/reports'
    | '/schemes'
    | '/settings'
    | '/farmer/applications'
    | '/farmer/apply'
    | '/farmer/grievance'
    | '/farmer/profile'
    | '/farmer'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/farmer'
    | '/login'
    | '/_app/analytics'
    | '/_app/applications'
    | '/_app/dashboard'
    | '/_app/field-verification'
    | '/_app/fraud'
    | '/_app/gis'
    | '/_app/grievances'
    | '/_app/reports'
    | '/_app/schemes'
    | '/_app/settings'
    | '/farmer/applications'
    | '/farmer/apply'
    | '/farmer/grievance'
    | '/farmer/profile'
    | '/farmer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  FarmerRoute: typeof FarmerRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/profile': {
      id: '/farmer/profile'
      path: '/profile'
      fullPath: '/farmer/profile'
      preLoaderRoute: typeof FarmerProfileRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/grievance': {
      id: '/farmer/grievance'
      path: '/grievance'
      fullPath: '/farmer/grievance'
      preLoaderRoute: typeof FarmerGrievanceRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/apply': {
      id: '/farmer/apply'
      path: '/apply'
      fullPath: '/farmer/apply'
      preLoaderRoute: typeof FarmerApplyRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/applications': {
      id: '/farmer/applications'
      path: '/applications'
      fullPath: '/farmer/applications'
      preLoaderRoute: typeof FarmerApplicationsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schemes': {
      id: '/_app/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof AppSchemesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grievances': {
      id: '/_app/grievances'
      path: '/grievances'
      fullPath: '/grievances'
      preLoaderRoute: typeof AppGrievancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gis': {
      id: '/_app/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof AppGisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fraud': {
      id: '/_app/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof AppFraudRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/field-verification': {
      id: '/_app/field-verification'
      path: '/field-verification'
      fullPath: '/field-verification'
      preLoaderRoute: typeof AppFieldVerificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFieldVerificationRoute: typeof AppFieldVerificationRoute
  AppFraudRoute: typeof AppFraudRoute
  AppGisRoute: typeof AppGisRoute
  AppGrievancesRoute: typeof AppGrievancesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSchemesRoute: typeof AppSchemesRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApplicationsRoute: AppApplicationsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFieldVerificationRoute: AppFieldVerificationRoute,
  AppFraudRoute: AppFraudRoute,
  AppGisRoute: AppGisRoute,
  AppGrievancesRoute: AppGrievancesRoute,
  AppReportsRoute: AppReportsRoute,
  AppSchemesRoute: AppSchemesRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface FarmerRouteChildren {
  FarmerApplicationsRoute: typeof FarmerApplicationsRoute
  FarmerApplyRoute: typeof FarmerApplyRoute
  FarmerGrievanceRoute: typeof FarmerGrievanceRoute
  FarmerProfileRoute: typeof FarmerProfileRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerApplicationsRoute: FarmerApplicationsRoute,
  FarmerApplyRoute: FarmerApplyRoute,
  FarmerGrievanceRoute: FarmerGrievanceRoute,
  FarmerProfileRoute: FarmerProfileRoute,
  FarmerIndexRoute: FarmerIndexRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  FarmerRoute: FarmerRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
